---
title: Accessible by Design
author: Caspian Turner
email: caspian@accessiblebydesign.co.uk
description: ''
baseurl: "/ubuild-jekyll"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
